### ISSUE TITLE
Example not working on OS X

### ISSUE THREAD

**Issue by patrickhulce** [WPO-Foundation/tsproxy#14]
Perhaps this is a Chrome issue, or I'm not doing some other necessary steps, or I've made some obvious mistakes in my commands (in which case I'd want this bug to morph into adding helpful hints about common misconfiguration 😄 ) but the example out of the box doesn't seem to be consistently working. It's also very hard to tell if it is working when subtle thresholds are applied...

Here are the commands I ran and the logs after trying to load theverge.com. If I'm reading things correctly, it looks like it's only trying to use the proxy for google connections and it's failing? Anything obvious I'm missing here?

## Chrome
`/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --proxy-server="socks://localhost:1080" --no-first-run --user-data-dir=/tmp/foobar 'about:blank'`

logs
```
[91547:37635:0419/175217.014768:ERROR:ssl_client_socket_impl.cc(1053)] handshake failed; returned -1, SSL error code 1, net_error -100
[91547:37635:0419/175219.802210:ERROR:ssl_client_socket_impl.cc(1053)] handshake failed; returned -1, SSL error code 1, net_error -100
[91547:37635:0419/175238.810694:ERROR:ssl_client_socket_impl.cc(1053)] handshake failed; returned -1, SSL error code 1, net_error -100
```

## tsproxy
command
`python tsproxy.py -vvvv -r 1000 -i 1677 -o 768` (I started with 150, but I couldn't tell if it was working so switch to 1000 to make sure it wasn't)

logs
```
17:52:11.431 - [43] Connected to clients4.google.com
17:52:11.431 - [43] SOCKS <= 26 byte(s)
17:52:11.431 - [43] SOCKS => 203 byte(s)
17:52:14.886 - [43] Server Connection Closed
17:52:17.014 - [44] Connected to clients4.google.com
17:52:17.014 - [44] SOCKS <= 26 byte(s)
17:52:17.014 - [43] Server connection close being processed, closing Browser connection
17:52:17.014 - [43] Browser Connection Closed by browser
17:52:17.014 - [44] SOCKS => 203 byte(s)
17:52:19.801 - [44] Server Connection Closed
17:52:19.802 - [44] Server connection close being processed, closing Browser connection
17:52:19.802 - [44] Browser Connection Closed by browser
17:52:19.803 - [45] Incoming connection from ('127.0.0.1', 63558)
17:52:19.803 - [45] New Socks5 client
17:52:19.803 - [45] SOCKS <= 2 byte(s)
17:52:23.447 - [46] Incoming connection from ('127.0.0.1', 63584)
17:52:23.447 - [46] New Socks5 client
17:52:23.447 - [46] SOCKS <= 2 byte(s)
17:52:28.019 - [45] Connecting to 172.217.5.110:443
17:52:28.790 - [45] Connected
17:52:31.731 - [46] Connecting to 172.217.5.110:443
17:52:32.410 - [46] Connected
17:52:36.223 - [45] Connected to clients4.google.com
17:52:36.223 - [45] SOCKS <= 26 byte(s)
17:52:36.223 - [45] SOCKS => 203 byte(s)
17:52:38.809 - [45] Server Connection Closed
```

I also couldn't get tsproxy to work in a ubuntu docker container, status was difficult to check and navigation over Chrome RDP failed with a 'cannot find proxy'. I can file a separate issue with repro steps if it still doesn't work after finding why OS X doesn't work :)

**Comment by paulirish** [comment]
fwiw here's an excerpt from [a setup i used when testing h2 push](https://gist.github.com/paulirish/076de2703cb6f3a980a30a983f002174#start-tsproxy-and-chrome):


```sh
python tsproxy.py --rtt=150 --inkbps=1600 --outkbps=768 --port=9996 -vvv

chrome-debug  --proxy-server="socks://localhost:9996"
```

I just tested this out again and it's peachy. Maybe using an explicit and alternative port is the trick?  Other than that I don't see anything in particular..

**Comment by patrickhulce** [comment]
Yeah it's still very buggy for me. If I copy and paste your commands verbatim, the first page load works and is appropriately throttled, once I connect over the protocol though one of two things happen.

* No site can be loaded at all, and I get the "This site can’t be reached theverge.com took too long to respond." message.
* No throttling is applied at all.

**Comment by pmeenan** [comment]
Connect over dev tools protocol?  Telemetry uses it as well so I don't think the protocol itself causes issues but maybe there is some sort of interaction that is causing the proxy settings to change or otherwise loop.

Any chance you can collect a netlog of both it working and when it is in a failed state?  That would help track down what Chrome is doing.

**Comment by patrickhulce** [comment]
Sure attached below, the devtools protocol does appear to be unrelated. My repro case is simply that every navigation after the first navigation fails. Additionally, the first navigation appears to be *much* slower than the latency numbers given. Applying 150ms RTT yields a load time 2-3x greater than when using Apple's Network Link Conditioner with 150ms latency.

[first navigation to theverge.com](https://drive.google.com/a/chromium.org/file/d/0B_6m1yW__xllTzRTd1dPWkVjODg/view?usp=sharing)
[second navigation to espn.com](https://drive.google.com/a/chromium.org/file/d/0B_6m1yW__xllVC15YlZYcENCOGc/view?usp=sharing)

**Comment by soulgalore** [comment]
I also have the some problems like the ones in https://github.com/WPO-Foundation/tsproxy/issues/10  and sites that can't be loaded on Mac. Let me know if more netlogs would help. Do you have any recommendations for the current version, is it best to use Windows or a specific Unix flavor?

**Comment by soulgalore** [comment]
Any updates on this? I'm just curios if there are any OS that is preferred that I can try?

**Comment by pmeenan** [comment]
Could be worth re-testing. I just fixed an issue with the clocks on Mac that was causing all sorts of screwy behavior: https://github.com/WPO-Foundation/tsproxy/commit/f0ab7517a907cb16c8f67965b05c740a32848112

That's what I get for initially doing all of the dev work on Windows and not realizing python can be so insane. time.clock() on Windows measures elapsed time but on other platforms (or at least Mac) it measures elapsed CPU time so for an idle proxy it would take seconds to tick for every 1ms of measured time.

**Comment by soulgalore** [comment]
@pmeenan thanks! I tested and it works much better for me. I'm gonna run some more test later on but with the ones I've done now (on Mac OS X) the result looks like as with with tc on Linux. This is great because it could potentially help people that want to run tests on Kubernetes, since there's no way today to throttle the traffic.
