### ISSUE TITLE
tsproxy delaying network traffic more than expected

### ISSUE THREAD

**Issue by acreskeyMoz** [WPO-Foundation/tsproxy#18]
There are two tsproxy behaviors that I don't understand and one may be a bug:

**1.**
A small amount of introduced latency (e.g. 100ms rtt) leads to multi-second response times.

Launch tsproxy as follows:
`python tsproxy.py --rtt=100`

Record the response time when making curl requests through tsproxy
`curl -w "%{time_total}\n" -o /dev/null  http://www.example.com --socks5-hostname 127.0.0.1:1080`

The initial total time for the request will be something close to 3 seconds, e.g. `2.887333`

If I launch trsproxy with a 1 second rtt then I see response times from curl at around 25 seconds.
 This is puzzling me as I don't see how a 1-second rtt could lead to a 25 second total response time. (Note that this test url wasn't event https. With https it jumps to ~43seconds).

This traffic delay also doesn't match the behavior of other traffic shaping tools. I've tried sitespeed.io's throttle and MacOS Network Link Conditioner (which I believe both use pfctl).

**2.**  
Subsequent requests by curl through tsproxy will be significantly faster.
For example, with 100ms rtt, the first response will take ~`2.887333` seconds but then subsequent requests will result in total times of something like `1.846140` seconds.   The difference, according to curl, is a reduction in "time_connect - start until the TCP connect to the remote host (or proxy) was completed".

Which makes me think that this is just tsproxy maintaining a socket connection to the destination host, and therefore not a bug.

**Comment by soulgalore** [comment]
Hi @acreskeyMoz I guess then you where testing with the new fix from Pat https://github.com/WPO-Foundation/tsproxy/commit/f0ab7517a907cb16c8f67965b05c740a32848112 ? Wanted to verify. I did some testig before and it looked better with that fix but I didn't spend so much time to verify.

**Comment by acreskeyMoz** [comment]
Hi @soulgalore -- actually my `tsproxy` doesn't include that fix.
Let me give that try.

**Comment by acreskeyMoz** [comment]
Thank you @soulgalore - the fix from [f0ab751](https://github.com/WPO-Foundation/tsproxy/commit/f0ab7517a907cb16c8f67965b05c740a32848112) drastically reduced the response time.

The total time for 
`curl -w "%{time_total}\n" -o /dev/null https://www.example.com --socks5-hostname 127.0.0.1:1080`  with `tsproxy` at `--rtt=100`
drops from ~ `4.3` seconds to ~`0.64` seconds with the fix (MacOS).

This is roughly in line with other throttling tools that I'm looking at.

I will assume that subsequent requests through `tsproxy` are faster than the initial since it persists tcp connections to the destination server.

I'm happy to close this one and thanks for the quick response.

**Comment by pmeenan** [comment]
Subsequent requests shouldn't be faster from persistence. If I had to guess it would be the DNS lookup which would be cached by the OS. Since it is a socks 5 proxy, every connection from the client results in a 1:1 connection from tsproxy.

Glad to hear things are looking better after the fixes.
