### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/tsproxy#2]
Hey Pat,
what's the current status of tsproxy? I've read the Google docs and me & @beenanner have just started testing it and tested it with Browsertime. I really like the idea and it works fine for us but I haven't tested how accurate it is. Have you had time to do any testing? Can I help out? 

With the minimal testing I've done on my local, I got the feeling that the first request takes longer time than with other tools emulating the same shaping, and that the RTT differs but this only a hunch I have, I haven't done any serious testing.

Best
Peter

**Comment by pmeenan** [comment]
It's complete AFAIK.  The Chrome team is integrating it with telemetry right now to use for the Chrome perf regression testing.

As far as testing goes, I configured Chrome to proxy through it and ran a bunch of html5 speed tests (that also measure latency) and things looked like they were behaving correctly (note, the upstream bandwidth shaping is correct but the speed test apps are really spiky when they measure it).

**Comment by soulgalore** [comment]
cool thanks :)
