### ISSUE TITLE
latest version can not work

### ISSUE THREAD

**Issue by zhbhun** [WPO-Foundation/tsproxy#21]
[Latest version](https://github.com/WPO-Foundation/tsproxy/tree/0f4b83fcb47a948d766d948964e30a34961bd6d4) output following errors(on ubuntu 16.04):

Traceback (most recent call last):
  File "tsproxy.py", line 158, in tick
    self.available_bytes -= self.next_message['size']
TypeError: 'NoneType' object has no attribute '__getitem__'
17:01:28.468 - Tick Exception

And, old version does work —— https://github.com/WPO-Foundation/tsproxy/tree/6ccc0eb5a8d308608d155545d265bd425765d724.

**Comment by soulgalore** [comment]
Yeah I get the same thing. [Last commit](https://github.com/WPO-Foundation/tsproxy/commit/0f4b83fcb47a948d766d948964e30a34961bd6d4) makes it not work for me either. When I tested without that commit, it works.I did't run in verbose mode but can do it if it helps. By "not work" I mean no traffic was coming through.
