### ISSUE TITLE
Q: How to use it with firefox?

### ISSUE THREAD

**Issue by plesiecki** [WPO-Foundation/tsproxy#24]
Hello,

Honest question. How to use it with firefox?

✌️

**Comment by pmeenan** [comment]
Manually: https://www.howtogeek.com/293213/how-to-configure-a-proxy-server-in-firefox/

(manual proxy config, fill in the socks details).

Through extension: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings

or in code through setting the prefs, there are a bunch of network.proxy.* prefs
