### ISSUE TITLE
issue with tsproxy connecting 

### ISSUE THREAD

**Issue by RajyAnand** [WPO-Foundation/tsproxy#3]
hi

i was able to setup tsproxy at machine and execute the python script with rtt, upload and download bw in kbps.  After this i was trying to use this proxy setup in my linux box as proxy setting in my mobile phone.  The expectation was the mobile will connect to internet thro this proxy in my linux.  but it was not able to connect to internet.  Also i got there is an issue with proxy setting.  can some one take a look of this issue  pls

i also tried to connect to my linux box thro ssh, and i could see the requests to my linux box happening thro, but the connections to the other urls(like google.com ) was not going out

we need this for shaping our mobile bandwidth and a quick support on this helps

Regards
Rajy

**Comment by pmeenan** [comment]
If you are connecting from a separate device you will need to specify the interface to listen on.  By default it only listens on localhost (which won't be reachable from another device).  Also, make sure whatever firewall you are running on the linux box (if enabled) is configured to allow external access to the port you are running the proxy on.

If you run it with -vvvv it will output a lot of debug information showing new connections, outbound requests, etc which will also help debugging your setup.

**Comment by RajyAnand** [comment]
hi
I tried listening from same device, which means i setup proxy on linux box and initiate web requests(from firefox/chrome browser with proxy settings on) to google search with different search keywords(to avoid caching).  Still i dont see a change in speed after throttling.  I was wondering if the proxy is setup correctly.  

Also can u pls explain what do u mean by interface when connecting from external device.  The scenario i am trying to setup is - I am trying to connect my mobile phone to this proxy setup in my linux box thro the wifi, so that i can change the network bandwidth thro the tsproxy running in my linux and my phone connects to this throttled bandwidth

RegardsRajalekshmy

```
On Tuesday, 2 August 2016 6:58 PM, Patrick Meenan <notifications@github.com> wrote:
```

 If you are connecting from a separate device you will need to specify the interface to listen on. By default it only listens on localhost (which won't be reachable from another device). Also, make sure whatever firewall you are running on the linux box (if enabled) is configured to allow external access to the port you are running the proxy on.If you run it with -vvvv it will output a lot of debug information showing new connections, outbound requests, etc which will also help debugging your setup.—

**Comment by pmeenan** [comment]
What command-line did you use to enable the proxy on your local machine when using Chrome?  What command line did you use to launch the proxy?  Did you see debug console output in the shell for the proxy indicating connections were coming in?

The second scenario is where you need to use the --bind option to tell it to bind to the IP address of your linux box that the mobile phone will be connecting to.  By default it listens to localhost only so it will only accept connections from browsers on the same machine.

**Comment by RajyAnand** [comment]
I executed the below in the command prompt
python tsproxy.py --rtt=200 --inkbps=1600 --outkbps=768

got msg on the screen "Started socks 5 proxy server on 127.0.0.1:1080 hit ctrl-c to exit"

After this i opened chrome browser on the desktop to see if the bandwidth is throttled.  i could not see any change, as if the proxy is not running

For the second scenario, in my phone i changed the settings under network connection to use the proxy i created.  i gave my linux server url as the proxy url and port is 1080.  After this i tried connecting to the chrome browser and tried browsing google.com, and got the error "page could not be opened"  Again i felt proxy is not set right

**Comment by pmeenan** [comment]
You should use:

```
python tsproxy.py -vvvv --bind 1.2.3.4 --rtt=2-- ==inkbps=1600 --outkbps=768
```

To launch Chrome you need to make sure to give it the SOCKS proxy command-line:

```
chrome --proxy-server="socks://1.2.3.4:1080"
```

And replace 1.2.3.4 with the actual IP address of your linux box in both cases.

**Comment by pmeenan** [comment]
btw, it's worth noting that speedtest.net uses flash sockets to do the bandwidth test and those are not proxied so make sure to test performance using something else.

**Comment by RajyAnand** [comment]
hi
I used  Drony(download from google playstore) to bind the mobile phone with the proxy.  The connection could be finally established from the phone to the proxy setup by tsproxy.  The open issues now i am facing are
- When i test the speed of the network on the phone thro "speed test" app(downloaded from playstore) it shows network speed of 15Mbps, where as the one i have set thro tsproxy is in the order of kbps.  Somewhere i see there is a gap.  
- When i vary the inkbps/outkbps of the network to from 256kbps to 512kbps to 1mbps, i dont see the effect of this change from mobile page load in browser.  At times i see slow loading due to throttling, but not able to see it always.    
- When i kill the tsproxy run(thro ctrl C), sometimes i get "page cannot be loaded" from mobile browser, but at times i am able to load the page succesfully.     

Also i was curious to know where i can go thro the logs of the proxy running from tsproxy.  This will help us understand the requests that are reaching the proxy and any errors emitted to the same
Also pls suggest if there are any better alternates to the Drony app, I am using for binding the proxy ip with mobile phone

Appreciate your support here in getting these issues resolved

RegardsRajalekshmy

```
On Tuesday, 2 August 2016 9:55 PM, Rajy Anand <rajy_anand@yahoo.com> wrote:
```

 hi
I tried listening from same device, which means i setup proxy on linux box and initiate web requests(from firefox/chrome browser with proxy settings on) to google search with different search keywords(to avoid caching).  Still i dont see a change in speed after throttling.  I was wondering if the proxy is setup correctly.  

Also can u pls explain what do u mean by interface when connecting from external device.  The scenario i am trying to setup is - I am trying to connect my mobile phone to this proxy setup in my linux box thro the wifi, so that i can change the network bandwidth thro the tsproxy running in my linux and my phone connects to this throttled bandwidth

RegardsRajalekshmy

```
On Tuesday, 2 August 2016 6:58 PM, Patrick Meenan <notifications@github.com> wrote:
```

 If you are connecting from a separate device you will need to specify the interface to listen on. By default it only listens on localhost (which won't be reachable from another device). Also, make sure whatever firewall you are running on the linux box (if enabled) is configured to allow external access to the port you are running the proxy on.If you run it with -vvvv it will output a lot of debug information showing new connections, outbound requests, etc which will also help debugging your setup.—

**Comment by pmeenan** [comment]
If you run tsproxy with the -vvvv command-line option (see above replies) it will display debug logging about every connection.  You can also run tcpdump on the host machine if you want to see if the mobile traffic is running through it during speed testing.

Sorry, I don't know anything about drony or configuring android devices system-wide to use a proxy.
