### ISSUE TITLE
Problems with http -> https redirects

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/tsproxy#6]
Hi Pat,
for some URLs I have problems with redirect from http to https, where the redirect fails (meaning the https version doesn't load) using the proxy (but without the proxy, it loads in Chrome). Two examples http://www.svenskaturistforeningen.se and http://booli.se 

I also have another category of problems for redirects: When I use Selenium to drive Chrome there are other URLs that doesn't work with the proxy, but they work when I use Chrome standalone with the proxy, so it's some kind ofa  Selenium issue (they work though using Selenium -> Firefox -> tsproxy). So it's something with Selenium and Chrome. Don't expect you to know why but maybe you know where to look? Example URLs that fails then is http://www.mp.se http://byggahus.se http://www.hhs.se

Best
Peter

**Comment by pmeenan** [comment]
Any chance you can try with current ToT?  There was a [fix](https://github.com/WPO-Foundation/tsproxy/commit/16761160e67ee9559d99f41142b55df88e632d87) for some of the port mapping logic that may have been causing issues ~5 days ago.

If it still fails, what command-line do you use to run the proxy and what do you use for the browser so I can make sure I'm reproducing it the same way?

**Comment by soulgalore** [comment]
Argh, I've missed that update! Updated now and it works fine.
